# Generated by Django 4.1.13 on 2024-09-30 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('apartment_number', models.CharField(blank=True, max_length=20, verbose_name='Apartment Number')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Zip Code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('property_type', models.IntegerField(choices=[(1, 'Studio Apartment'), (2, 'Loft Apartment'), (3, 'Penthouse Apartment'), (4, 'Detached House'), (5, 'Semi-detached House'), (6, 'Bungalow'), (7, 'Cottage'), (8, 'Villa'), (9, 'High-rise Condo'), (10, 'Low-rise Condo'), (11, 'Row Townhouse'), (12, 'End-unit Townhouse'), (13, 'Residential Land'), (14, 'Commercial Land'), (15, 'Agricultural Land'), (16, 'Industrial Land')], default=1, verbose_name='Property Type')),
                ('status', models.IntegerField(choices=[(1, 'For Sale'), (2, 'Sold'), (3, 'Rental'), (4, 'Leased'), (5, 'Unavailable')], default=1, verbose_name='Status')),
                ('condition', models.IntegerField(choices=[(1, 'New'), (2, 'Used'), (3, 'Renovated')], default=2, verbose_name='Condition')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price')),
                ('currency', models.IntegerField(choices=[(1, 'US Dollar'), (2, 'Euro'), (3, 'British Pound'), (4, 'Naira'), (5, 'Ghana Cedis')], default=1, verbose_name='Currency')),
                ('area', models.DecimalField(decimal_places=2, help_text='in square meters', max_digits=10, verbose_name='Area')),
                ('bedrooms', models.IntegerField(verbose_name='Bedrooms')),
                ('bathrooms', models.IntegerField(verbose_name='Bathrooms')),
                ('floors', models.IntegerField(verbose_name='Floors')),
                ('year_built', models.IntegerField(verbose_name='Year Built')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.address')),
                ('agents', models.ManyToManyField(related_name='listed_properties', to='account.agent')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('attribute_type', models.CharField(choices=[('amenity', 'Amenity'), ('feature', 'Feature')], max_length=20, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.country')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', verbose_name='Image')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAttributeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='Value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertyattribute')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_assignments', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('view', 'View'), ('favorite', 'Favorite'), ('inquiry', 'Inquiry'), ('review', 'Review')], max_length=20, verbose_name='Activity Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('details', models.JSONField(default=dict, verbose_name='Details')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='attributes',
            field=models.ManyToManyField(through='properties.PropertyAttributeAssignment', to='properties.propertyattribute'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.region')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.city'),
        ),
    ]
